#ifndef HEADERS_H
#define HEADERS_H
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>
#include <QWidget>
#include <QComboBox>
#include <QToolButton>
#include <QDateTimeEdit>
#include <QTableWidget>
#include <QTabWidget>
#include <QLine>
#include <QStringList>
#include <QListWidget>
#include <QTreeWidget>
#include <QRegExp>
#include <QSettings>
#include <QTextCodec>
#include <minwindef.h>
#include <QDebug>
#include <QMouseEvent>
#include <QPalette>
#include <QTimer>
#include <QTcpSocket>
#include <QTextBrowser>
#include "recvthread.h"
#include "sendthread.h"
#include "qchartviewer.h"
#endif // HEADERS_H
